version: '3.7'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=lojapet
    volumes:
      - postgres-data:/bitnami/postgresql
    ports:
      - '5432:5432'

volumes:
  postgres-data:
    driver: local
